# Sample Jekyll Picture Tag settings

picture:
  asset_path: "assets/images"
  generated_path: "assets/images/generated"
  markup: picturefill
  presets:
    default:
      ppi: [1, 1.3, 2]
      attr:
        class: "blogimage"
        itemprop: "image"
      source_lrg:
        media: "(min-width: 90em)"
        width: "1000"
      source_med:
        media: "(min-width: 60em)"
        width: "750"
      source_default:
        width: "500"
        height: "200"
    gallery:
      attr:
        data-image: "gallery"
      source_wide_hi:
        media: "(min-width: 60em) and (min-resolution: 1.5dppx)"
        width: "750"
        height: "450"
      source_wide:
        media: "(min-width: 60em)"
        width: "375"
        height: "225"
      source_default:
        width: "250"
        height: "150"
