# Sample Jekyll Picture Tag settings
### Run through the image sizes and make sure they make sense

picture:
  asset_path: "assets/images"
  generated_path: "assets/images/generated"
  markup: "picturefill"
  presets:
    default:
      ppi: [1, 1.3, 2]
      attr:
        class: "blogimagefull"
        itemprop: "image"
      source_lrg:
        media: "(min-width: 90em)"
        width: "800"
      source_med:
        media: "(min-width: 60em)"
        width: "650"
      source_default:
        width: "500"
        height: "200"
    # A half width variation for blog posts
    half:
      ppi: [1, 1.3, 2]
      attr:
        class: "blogimagehalf"
        itemprop: "image"
      source_lrg:
        media: "(min-width: 90em)"
        width: "400"
      source_med:
        media: "(min-width: 60em)"
        width: "325"
      source_default:
        width: "250"
        height: "100"
    # A lead image for the front page of your site
    hero:
      ppi: [1, 1.3, 2, 3]
    gallery:
      attr:
        data-image: "gallery"
      source_wide_hi:
        media: "(min-width: 90em) and (min-resolution: 1.5dppx)"
        width: "525"
        height: "525"
      source_wide:
        media: "(min-width: 90em)"
        width: "350"
        height: "350"
      source_default:
        width: "250"
        height: "250"
